---
abstract: 'A Modern Perl Framework for High Throughput Sequencing analysis'
author:
  - "Emmanouil \"Manolis\" Maragkakis <mns.marag@gmail.com>, Panagiotis Alexiou <pan.alexiou@gmail.com>"
build_requires:
  Test::Class: 0
  Test::Class::Load: 0
  Test::Class::Moose: 0
  Test::Class::Moose::Load: 0
  Test::Class::Moose::Role::AutoUse: 0
  Test::Exception: 0
  Test::Moose: 0
  Test::More: 0
  Test::Most: 0
  base: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: GenOO
requires:
  DBI: 0
  DBIx::Class::Core: 0
  DBIx::Class::Schema: 0
  IO::Zlib: 0
  Modern::Perl: 0
  Moose: 0
  Moose::Role: 0
  Moose::Util::TypeConstraints: 0
  MooseX::AbstractFactory: 0
  MooseX::MarkAsMethods: 0
  autodie: 0
  namespace::autoclean: 0
  strict: 0
version: 1.4.3
